spring:
  cloud:
    config:
      name: stock-api
      profile: dev
      label: latest

  config:
    import:
    - configserver:http://localhost:9000

  datasource:
      url: jdbc:postgresql://localhost:5432/pit
      username: admin
      password: Admin@123
      driverClassName: org.postgresql.Driver
      hikari:
        connectionTimeout: 20000
        maximumPoolSize: 5
        
  jpa:
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
