spring:
  cloud:
    config:
      name: stock-api
      profile: dev

  config:
    import:
    - configserver:http://localhost:9000

  data:
      mongodb:
        username: stock
        password: Stock@123
        database: stock
        host: localhost
        port: 27017
        authentication-database: admin
       
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      