spring:
  cloud:
    config:
      name: stock-api
      profile: dev

  config:
    import:
    - configserver:http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/